name: term
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_3
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_3
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyh0d26453_0
  - python=3.14.1=h1858270_100_cp314
  - python_abi=3.14=2_cp314
  - readline=8.3=h0b18652_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - datetime==6.0
      - dotenv==0.9.9
      - fonttools==4.61.0
      - idna==3.11
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - numpy==2.3.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - six==1.17.0
      - threadpoolctl==3.6.0
      - tzdata==2025.2
      - urllib3==2.6.0
      - zope-interface==8.1.1
prefix: /opt/anaconda3/envs/term
